### ISSUE TITLE
Passar para o plural

### ISSUE THREAD

**Issue by gbessa** [outtec/timesheet-api#3]
Na verdade coloca o nome base do recurso no RequestMapping da classe, para não ficar repetitivo.

Ex:
@RestController
@RequestMapping("api/v1/timesheets")
@CrossOrigin(origins = "*")
public class TimesheetController {

https://github.com/outtec/timesheet-api/blob/785f9eba926572d41a1c1529ec01f02509abc88c/src/main/java/br/com/outtec/timesheetapi/controllers/TimesheetController.java#L85

**Comment by JoyceAquino** [comment]
feito

**Comment by gbessa** [comment]
Então, deixa para fechar no pull request. pois é o momento que eu vou verificar o codigo. a sua branch ainda nem está no github para eu ver.
