### ISSUE TITLE
Não íamos fazer tudo interno em inglês?

### ISSUE THREAD

**Issue by gbessa** [outtec/timesheet-api#5]
https://github.com/outtec/timesheet-api/blob/785f9eba926572d41a1c1529ec01f02509abc88c/src/main/java/br/com/outtec/timesheetapi/services/TimesheetService.java#L24

**Comment by JoyceAquino** [comment]
Vou acertar hoje, dei mole.

**Comment by JoyceAquino** [comment]
acertei, ta na branch que estou trabalhando.
